<!--- begin header --->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Free Public DNS Servers</title>
    <meta name="keywords" content="List of Public DNS Servers, public dns servers, public dns server, public caching server, free dns servers,dns servers" />
    <meta name="description" content="List of free public dns servers" />
    <meta name="author" content="Webmaster"/>
    <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="must-revalidate"/>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu+Mono" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css" rel="stylesheet">
    <link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
