<center>
<table width=40%>
<tr>
        <td align=left>
		<table width=50%>
		<tr>
        		<td align=left>
				<?php
                		include 'adds/google_add.inc';
				?>
                		<table class=table>
                		<tr valign=bottom>
					<td>
                                		<font size=6><b>FixYourIP</font>
                        		</td>
                        		<td>
                                		<font size=3><b><a href=/index.php>Home</a></b></font>
                        		</td>
                        		<td>
                                		<font size=3><b><a href=/tools>Tools</a></b></font>
                        		</td>
                        		<td>
                                		<font size=3><b><a href=/aboutus.php>About</a></b></font>
                        		</td>
                        		<td>
                                		<font size=3><b><a href=/library/>Library</a></b></font>
                        		</td>
					<td>
                                                <font size=3><b><a href=/reports/>Report</a></b></font>
                                        </td>
                		</tr>
                		</table>
                		<br>
        		</td>
		</tr>
		</table>
