<?php
set_include_path ('.:../includes:../../includes');
include 'ssltools.inc';

echo "<center>";
echo "<table width=50%>";
echo "<tr>";
        echo "<td align=left>";
                include 'adds/google_add.inc';
                echo "<br>";
                echo "<table class=table>";
                echo "<tr valign=bottom>";
			echo "<td>";
                                echo "<font size=6><b>FixYourIP</font>";
                        echo "</td>";
			echo "<td>";
                                echo "<font size=3><b><a href=/index.php>Home</a></b></font>";
                        echo "</td>";
			echo "<td>";
                                echo "<font size=3><b><a href=/tools>Tools</a></b></font>";
                        echo "</td>";
                        echo "<td>";
                                echo "<font size=3><b><a href=/aboutus.php>About</a></b></font>";
                        echo "</td>";
                        echo "<td>";
                                echo "<font size=3><b><a href=/library/>Library</a></b></font>";
                        echo "</td>";
			echo "<td>";
                                echo "<font size=3><b><a href=/reports/>Reports</a></b></font>";
                        echo "</td>";
                echo "</tr>";
                echo "</table>";
                echo "<br>";
        echo "</td>";
echo "</tr>";
echo "</table>";
echo "</center";

echo "<center>";
echo "<table width=50%>";
echo "<tr>";
        echo "<td align=left>";
                print ('<b>YourIP:</b> '.$_SERVER['REMOTE_ADDR'].'');
                echo "<br>";
                echo "<b>Hostname: </b>";
                echo  shell_exec('dig -4 +short -x '.$_SERVER['REMOTE_ADDR'].'');
		echo "<br><br>";
        echo "</td>";
        echo "<td>";
echo "</tr>";
echo "</table>";
echo "</center";

echo "<center>";
echo "<table width=50%>";

echo "<tr>";
	echo "<td align=left>";
		echo "<form action=/net_resolve.php method=post>";
                echo "<h4>View Mail Server Certificate</h4>";
                echo "Enter IP or Hostname";
                echo "<br>";
                echo "<input type=text name=mailcert>";
                echo "<input type=hidden name=tool_option value=mailcert>";
                echo "<input type=submit value=check>";
                echo "<br><br>";
                echo "</form>";
	echo "</td>";
	echo "<td>";
		echo "<form action=/net_resolve.php method=post>";
                echo "<h4>View Web Server Certificate</h4>";
                echo "Enter IP or Hostname";
                echo "<br>";
                echo "<input type=text name=webcert>";
                echo "<input type=hidden name=tool_option value=webcert>";
                echo "<input type=submit value=check>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";
echo "</tr>";

echo "<tr>";
        echo "<td align=left>";
		echo "<form action=/net_resolve.php method=post>";
                echo "<h4>Check Certificate Validity </h4>";
                echo "Enter FQDN of server";
                echo "<br>";
                echo "<input type=text name=ip>";
                echo "<input type=hidden name=tool_option value=ssl>";
                echo "<input type=submit value=check>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";
        echo "<td>";
		echo "<form enctype=multipart/form-date action=convert_cert.php method=post>";
                echo "<h4>Display Certificate </h4>";
                echo "Choose Certificate to upload:";
		echo "<br>";
                echo "<input name=file type=file />";
                echo "<input type=hidden name=MAX_FILE_SIZE value=1000 />";
                echo "<input type=submit value=Upload File/>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";
echo "</tr>";

echo "<tr>";
        echo "<td align=left>";
		echo "<form enctype=multipart/form-date action=view_pkcs12.php method=post>";
                echo "<h4>Display PKCS12 Certificate </h4>";
                echo "Choose Certificate to upload:";
                echo "<br>";
                echo "<input name=file type=file />";
                echo "<input type=hidden name=MAX_FILE_SIZE value=1000 />";
                echo "<input type=password size=25 maxlength=25 name=passwd> Password";
                echo "<br>";
                echo "<input type=submit value='PKCS12 Viewer'/>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";
        echo "<td>";
                echo "<form enctype=multipart/form-date action=cert_upload.php method=post>";
                echo "<h4>Convert Certificate to PEM format</h4>";
                echo "Choose Certificate to upload:";
                echo "<br>";
                echo "<input name=file type=file />";
                echo "<input type=hidden name=MAX_FILE_SIZE value=1000 />";
                echo "<input type=submit value=Convert Certificate/>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";
echo "</tr>";

echo "<tr>";
	echo "<td align=left colspan=2>";
echo "</tr>";

echo "<tr>";
	echo "<td colspan=2>";
	echo "</td>";
echo "</tr>";
echo "</table>";

include 'lookups.inc';
echo "<br>";
include 'add1.inc';
echo "</center>";
include 'footer.inc';
?>
