<br>
<table border=0>
<tr>
	<td colspan=3 align=right>
		<br>
		<a href=/tools><font size=4><b>More Tools</b></font></a>
		<br><br>
	</td>
</tr>
<tr>
        <td>
		<div style=background-color:silver>
			<form action=/net_resolve.php method=post>
                	Check Mail Certificate<br>
                	<input type=text name=mailcert>
                	<input type=hidden name=tool_option value=mailcert>
                	<input type=submit value=check>
                	</form>
		</div>
        </td>

        <td>
		<div style=background-color:silver>
			<form action=/net_resolve.php method=post>
                        Check Web Certificate<br>
                        <input type=text name=webcert>
                        <input type=hidden name=tool_option value=webcert>
                        <input type=submit value=check>
                        </form>
		</div>
       </td>
	<td>
       </td>
</tr>

<tr>
        <td rowspan=2>
       </td>
</tr>
</table>
