<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Decode - Display Certifcate</title>
<meta name="keywords" content="display certificate, decode certificate" />
<meta name="description" content="Display contents of pem, der certificate" />
<meta name="author" content="Webmaster"/>
<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE"/>
<link href="/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
