</center>
<center>
<?php
include 'site_info.inc';
?>
<font size=2>Copyright &copy; 2008 - 2018 <a href="http://www.fixyourip.com">www.fixyourip.com</a>.</font>
</center>

<!--- Start google analytics --->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-744038-6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-744038-6');
</script>

<!--- end google analytics --->

</body>
</html>
