</center>
<center>
<?php
include 'site_info.inc';
?>
<font size=2>Copyright &copy; 2008 - 2018 <a href="http://www.fixyourip.com">www.fixyourip.com</a>.</font>
</center>

<!--- begine Google analytics --->
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- fixyourip-responsive -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-9703614120192799"
     data-ad-slot="1135709012"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

<!--- end google analytics --->

</body>
</html>
