</center>
<center>
<?php
include 'site_info.inc';
?>
<font size=2>Copyright &copy; 2008 - 2016 <a href="http://www.fixyourip.com">www.fixyourip.com</a>.</font>
</center>

<!--- begine Google analytics --->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-744038-6', 'auto');
  ga('send', 'pageview');

</script>
<!--- end google analytics --->

</body>
</html>
