<table width=50%>
<tr>
        <td align=left>
		<?php
                include 'adds/google_add.inc';
		?>
                <font size=5>FixYourIP</font>
	</td>
	<td align=right>
		<table>
		<tr>
        	<td>
                        <font size=3><b><a href=/index.php>Home</a></b></font>
                </td>
                <td>
                       <font size=3><b><a href=/aboutus.php>About</a></b></font>
                </td>
                <td>
                       <font size=3><b><a href=/library/>Library</a></b></font>
                </td>
		<td>
                       <font size=3><b><a href=/reports/>Reports</a></b></font>
                </td>
		</tr>
		</table>
        </td>
</tr>
</table>
