<?php
set_include_path ('.:../includes:../../includes');
include 'header_dns.inc';

echo "<center>";
echo "<table width=50%>";
echo "<tr>";
        echo "<td align=left>";
                include 'adds/google_add.inc';
                echo "<br>";
                echo "<table class=table>";
                echo "<tr valign=bottom>";
			          echo "<td>";
                echo "<h2>FixYourIP</h2>";
                echo "</td>";
			          echo "<td>";
                echo "<font size=3><b><a href=/index.php>Home</a></b></font>";
                echo "</td>";
			          echo "<td>";
                echo "<font size=3><b><a href=/tools>Tools</a></b></font>";
                echo "</td>";
                echo "<td>";
                echo "<font size=3><b><a href=/aboutus.php>About</a></b></font>";
                echo "</td>";
                echo "<td>";
                echo "<font size=3><b><a href=/library/>Library</a></b></font>";
                echo "</td>";
			          echo "<td>";
                                echo "<font size=3><b><a href=/reports/>Reports</a></b></font>";
                        echo "</td>";
                echo "</tr>";
                echo "</table>";
                echo "<br>";
        echo "</td>";
echo "</tr>";
echo "</table>";
echo "</center";

echo "<center>";
echo "<table width=50%>";
echo "<tr>";
        echo "<td align=left>";
                print ('<b>YourIP:</b> '.$_SERVER['REMOTE_ADDR'].'');
                echo "<br>";
                echo "<b>Hostname: </b>";
                echo  shell_exec('dig -4 +short -x '.$_SERVER['REMOTE_ADDR'].'');
		echo "<br><br>";
		echo "<g:plusone></g:plusone>";
        echo "</td>";
        echo "<td>";
echo "</tr>";
echo "</table>";
echo "</center";

echo "<center>";
echo "<table width=50%>";
echo "<tr>
	<td align=left>";
                echo "<h4>DNS Lookup (FQDN)</h4>";
                echo "Lookup A, MX, SOA, txt, cname records<br>";
		echo "<form action=../resolve_dns.php method=post>";
		echo "<input type=text name=ip>";
		echo "<select name=dns_options>";
			echo "<option value=a>A </option>";
			echo "<option value=mx>MX </option>";
			echo "<option value=cname>CNAME</option>";
			echo "<option value=ns>NS </option>";
			echo "<option value=soa>SOA </option>";
			echo "<option value=txt>TXT </option>";
			echo "<option value=aaaa>AAAA </option>";
			echo "<option value=ptr>PTR </option>";
			echo "<option value=hinfo>Hinfo </option>";
			echo "<option value=srv>SRV </option>";
			echo "<option value=any>Any </option>";
			echo "<option value=all>All </option>";
		echo "</select>";
		echo "<input type=submit value=check>";
                echo "<br><br>";
		echo "</form>";
	echo "</td>";
	echo "<td align=left>";
                echo "<form action=../net_resolve.php method=post>";
                echo "<h4>Advanced Whois Lookup</h4>";
                echo "IP or Domain<br>";
                echo "<input type=text name=whois>";
                echo "<input type=hidden name=tool_option value=whois>";
                echo "<input type=submit value=check>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";
echo "</tr>";

echo "<tr>";
        echo "<td align=left>";
		echo "<form action=../net_resolve.php method=post>";
                echo "<h4>Check Domain for SPF record</h4>";
                echo "Enter FQDN (Domain)";
                echo "<br>";
                echo "<input type=text name=ip>";
                echo "<input type=hidden name=tool_option value=spf>";
                echo "<input type=submit value=check>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";
        echo "<td align=left>";
                echo "<form action=../net_resolve.php method=post>";
                echo "<h4>Reverse IP Address Lookup </h4>";
                echo "Check if your IP has a reverse DNS entry";
                echo "<br>";
                echo "<input type=text name=ip>";
                echo "<input type=hidden name=tool_option value=reverseip>";
                echo "<input type=submit value=check>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";
echo "</tr>";

echo "<tr>";
        echo "<td align=left>";
                echo "<form action=../net_resolve.php method=post>";
                echo "<h4>Who hosts that Website (BETA)</h4>";
                echo "Enter web site address";
                echo "<br>";
                echo "<input type=text name=ip value=>";
                echo "<input type=hidden name=tool_option value=webhost>";
                echo "<input type=submit value=check>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";

	echo "<td align=left>";
                echo "<form action=../net_resolve.php method=post>";
                echo "<h4>Check DNS propogation.</h4>";
                echo "Enter FQDN of server";
                echo "<br>";
                echo "<input type=text name=ip value=>";
                echo "<input type=hidden name=tool_option value=dnspropogate>";
                echo "<input type=submit value=check>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";
echo "</tr>";
echo "<tr>";
        echo "<td align=left>";
                echo "<form action=../net_resolve.php method=post>";
                echo "<h4>DNS Zonecheck </h4>";
                echo "Enter Domain Name (google.com)";
                echo "<br>";
                echo "<input type=text name=zone>";
                echo "<input type=hidden name=tool_option value=zone>";
                echo "<input type=submit value=check>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";

        echo "<td align=left>";
                echo "<form action=../net_resolve.php method=post>";
                echo "<h4>DNS Trace </h4>";
                echo "Enter FQDN (www.google.com)";
                echo "<br>";
                echo "<input type=text name=dnstracer>";
                echo "<input type=hidden name=tool_option value=dnstracer>";
                echo "<input type=submit value=DNStracer>";
                echo "<br><br>";
                echo "</form>";
        echo "</td>";
echo "</tr>";

echo "<tr>";
	echo "<td align=left colspan=2>";
echo "</tr>";

echo "<tr>";
	echo "<td colspan=2>";
	echo "</td>";
echo "</tr>";
echo "</table>";

include 'lookups.inc';
echo "<br>";
include 'add1.inc';
echo "</center>";
include 'footer.inc';
?>
